var assert = require("assert");
var romajiName = require("./romaji-name");

romajiName.init(function() {
    var tests = [
        { original: 'Utagawa Toyokuni 3sei',
          locale: 'ja',
          generation: 3,
          given: 'Toyokuni',
          given_kana: 'とよくに',
          surname: 'Utagawa',
          surname_kana: 'うたがわ',
          name: 'Utagawa Toyokuni III',
          ascii: 'Utagawa Toyokuni III',
          plain: 'Utagawa Toyokuni III',
          kana: 'うたがわとよくに' },
        { original: '歌川 豊国 3世',
          locale: 'ja',
          generation: 3,
          surname_kanji: '歌川',
          given_kanji: '豊国',
          kanji: '歌川豊国' },
        { original: 'Sawa Sekkyō 沢雪キョウ',
          locale: 'ja',
          kanji: '雪キョウ沢',
          given: 'Sawa',
          given_kana: 'さわ',
          surname: 'Sekkyō',
          surname_kana: 'せっきょお',
          given_kanji: '沢',
          surname_kanji: '雪キョウ',
          name: 'Sekkyō Sawa',
          ascii: 'Sekkyoo Sawa',
          plain: 'Sekkyo Sawa',
          kana: 'せっきょおさわ' },
        { original: 'Hatta Koshu (八田古秀）',
          locale: 'ja',
          kanji: '八田古秀',
          given: 'Kōshū',
          given_kana: 'こおしゅう',
          surname: 'Hatta',
          surname_kana: 'はった',
          surname_kanji: '八田',
          given_kanji: '古秀',
          name: 'Hatta Kōshū',
          ascii: 'Hatta Kooshuu',
          plain: 'Hatta Koshu',
          kana: 'はったこおしゅう' },
        { original: 'Chōmei Ryoji',
          locale: 'ja',
          given: 'Chōmei',
          given_kana: 'ちょおめい',
          surname: 'Ryōji',
          surname_kana: 'りょおじ',
          name: 'Ryōji Chōmei',
          ascii: 'Ryooji Choomei',
          plain: 'Ryoji Chomei',
          kana: 'りょおじちょおめい' },
        { original: 'Kajiwara Hisako artist) - 梶原 緋佐子',
          locale: 'ja',
          surname_kanji: '梶原',
          given_kanji: '緋佐子',
          kanji: '梶原緋佐子',
          given: 'Hisako',
          given_kana: 'ひさこ',
          surname: 'Kajiwara',
          surname_kana: 'かじわら',
          name: 'Kajiwara Hisako',
          ascii: 'Kajiwara Hisako',
          plain: 'Kajiwara Hisako',
          kana: 'かじわらひさこ' },
        { original: 'Born Sato Kunio',
          locale: 'ja',
          given: 'Kunio',
          given_kana: 'くにお',
          surname: 'Sato',
          surname_kana: 'さと',
          name: 'Sato Kunio',
          ascii: 'Sato Kunio',
          plain: 'Sato Kunio',
          kana: 'さとくにお' },
        { original: 'Unidentied Chinese printmaker',
          locale: '',
          unknown: true },
        { original: 'Shotei fake',
          locale: 'ja',
          after: true,
          given: 'Shotei',
          given_kana: 'しょてい',
          name: 'Shotei',
          ascii: 'Shotei',
          plain: 'Shotei',
          kana: 'しょてい' },
        { original: 'Torii School',
          locale: 'ja',
          school: true,
          surname: 'Torii' },
        { original: 'Ryusai SHEGEHARU',
          locale: 'ja',
          given: 'Shigeharu',
          given_kana: 'しげはる',
          surname: 'Ryūsai',
          surname_kana: 'りゅうさい',
          name: 'Ryūsai Shigeharu',
          ascii: 'Ryuusai Shigeharu',
          plain: 'Ryusai Shigeharu',
          kana: 'りゅうさいしげはる' },
        { original: 'Hanabusa Itcho_',
          locale: 'ja',
          given: 'Itchō',
          given_kana: 'いっちょお',
          surname: 'Hanabusa',
          surname_kana: 'はなぶさ',
          name: 'Hanabusa Itchō',
          ascii: 'Hanabusa Itchoo',
          plain: 'Hanabusa Itcho',
          kana: 'はなぶさいっちょお' },
        { original: 'Ho_chu_',
          locale: 'ja',
          given: 'Hōchū',
          given_kana: 'ほおちゅう',
          name: 'Hōchū',
          ascii: 'Hoochuu',
          plain: 'Hochu',
          kana: 'ほおちゅう' },
        { original: 'Ito Jakuchu',
          locale: 'ja',
          given: 'Jakuchū',
          given_kana: 'じゃくちゅう',
          surname: 'Ito',
          surname_kana: 'いと',
          name: 'Ito Jakuchū',
          ascii: 'Ito Jakuchuu',
          plain: 'Ito Jakuchu',
          kana: 'いとじゃくちゅう' },
        { original: 'Jakuchu Ito',
          locale: 'ja',
          given: 'Jakuchū',
          given_kana: 'じゃくちゅう',
          surname: 'Ito',
          surname_kana: 'いと',
          name: 'Ito Jakuchū',
          ascii: 'Ito Jakuchuu',
          plain: 'Ito Jakuchu',
          kana: 'いとじゃくちゅう' },
        { original: 'artists other two and Katsushika Taito II',
          locale: 'ja',
          unknown: true },
        { original: 'Foujita',
          locale: '',
          given: '',
          surname: 'Foujita',
          name: 'Foujita',
          ascii: 'Foujita',
          plain: 'Foujita' },
        { original: 'Jacoulet',
          locale: '',
          given: '',
          surname: 'Jacoulet',
          name: 'Jacoulet',
          ascii: 'Jacoulet',
          plain: 'Jacoulet' },
        { original: 'Illustrations attributed to Gountei Sadahide (Japanese, 1807–1873)',
          locale: 'ja',
          attributed: true,
          given: 'Sadahide',
          given_kana: 'さだひで',
          surname: 'Gōntei',
          surname_kana: 'ごおんてい',
          name: 'Gōntei Sadahide',
          ascii: 'Goontei Sadahide',
          plain: 'Gontei Sadahide',
          kana: 'ごおんていさだひで' },
        { original: 'Printed by Professor Clifford Harvey',
          locale: '',
          given: 'Clifford',
          surname: 'Harvey',
          name: 'Clifford Harvey',
          ascii: 'Clifford Harvey',
          plain: 'Clifford Harvey' },
        { original: 'Katsukawa Shun&#x02bc;ei',
          locale: 'ja',
          given: 'Shun\'ei',
          given_kana: 'しゅんえい',
          surname: 'Katsukawa',
          surname_kana: 'かつかわ',
          name: 'Katsukawa Shun\'ei',
          ascii: 'Katsukawa Shun\'ei',
          plain: 'Katsukawa Shun\'ei',
          kana: 'かつかわしゅんえい' },
        { original: 'Numerous', locale: '', unknown: true },
        { original: 'Katsushika Hokusai to atributed',
          locale: 'ja',
          attributed: true,
          given: 'Hokusai',
          given_kana: 'ほくさい',
          surname: 'Katsushika',
          surname_kana: 'かつしか',
          name: 'Katsushika Hokusai',
          ascii: 'Katsushika Hokusai',
          plain: 'Katsushika Hokusai',
          kana: 'かつしかほくさい' },
        { original: 'Katsushika Hokusai of pupil A',
          locale: 'ja',
          school: true,
          given: 'Hokusai',
          given_kana: 'ほくさい',
          surname: 'Katsushika',
          surname_kana: 'かつしか',
          name: 'Katsushika Hokusai',
          ascii: 'Katsushika Hokusai',
          plain: 'Katsushika Hokusai',
          kana: 'かつしかほくさい' },
        { original: 'Imitator of Albrecht Dürer (20th century)',
          locale: '',
          after: true,
          given: 'Albrecht',
          surname: 'Dürer',
          name: 'Albrecht Dürer',
          ascii: 'Albrecht Dürer',
          plain: 'Albrecht Durer' },
        { original: 'Kasamatsu Shiro_',
          locale: 'ja',
          given: 'Shirō',
          given_kana: 'しろお',
          surname: 'Kasamatsu',
          surname_kana: 'かさまつ',
          name: 'Kasamatsu Shirō',
          ascii: 'Kasamatsu Shiroo',
          plain: 'Kasamatsu Shiro',
          kana: 'かさまつしろお' },
        { original: 'Utagawa Schule / Utagawa school',
          locale: 'ja',
          school: true,
          surname: 'Utagawa' },
        { original: 'unbekannt / unknown / michi',
          locale: '',
          unknown: true },
        { original: 'possibly Kubo Shunman (Japanese, 1757–1820)',
          locale: 'ja',
          given: 'Shunman',
          given_kana: 'しゅんまん',
          surname: 'Kubo',
          surname_kana: 'くぼ',
          name: 'Kubo Shunman',
          ascii: 'Kubo Shunman',
          plain: 'Kubo Shunman',
          kana: 'くぼしゅんまん' },
        { original: 'Kanbun artist',
          locale: 'ja',
          given: 'Kanbun',
          given_kana: 'かんぶん',
          name: 'Kanbun',
          ascii: 'Kanbun',
          plain: 'Kanbun',
          kana: 'かんぶん' },
        { original: 'Sakazosu or Sakazoshu',
          locale: 'ja',
          given: 'Sakazosu',
          given_kana: 'さかぞす',
          name: 'Sakazosu',
          ascii: 'Sakazosu',
          plain: 'Sakazosu',
          kana: 'さかぞす' },
        { original: 'Utagawa Toyokuni with Arisaka Hokuba & Katsukawa Shun\'ei',
          locale: 'ja',
          given: 'Toyokuni',
          given_kana: 'とよくに',
          surname: 'Utagawa',
          surname_kana: 'うたがわ',
          name: 'Utagawa Toyokuni',
          ascii: 'Utagawa Toyokuni',
          plain: 'Utagawa Toyokuni',
          kana: 'うたがわとよくに' },
        { original: 'Kawanabe Ky?sai',
          locale: 'ja',
          given: 'Kyōsai',
          given_kana: 'きょおさい',
          surname: 'Kawanabe',
          surname_kana: 'かわなべ',
          name: 'Kawanabe Kyōsai',
          ascii: 'Kawanabe Kyoosai',
          plain: 'Kawanabe Kyosai',
          kana: 'かわなべきょおさい' },
        { original: 'Shunk?sai Hokush?',
          locale: 'ja',
          given: 'Shunkosai',
          given_kana: 'しゅんこさい',
          surname: 'Hokushō',
          surname_kana: 'ほくしょお',
          name: 'Hokushō Shunkosai',
          ascii: 'Hokushoo Shunkosai',
          plain: 'Hokusho Shunkosai',
          kana: 'ほくしょおしゅんこさい' },
        { original: 'Seal KIYO',
          locale: 'ja',
          given: 'Kiyo',
          given_kana: 'きよ',
          name: 'Kiyo',
          ascii: 'Kiyo',
          plain: 'Kiyo',
          kana: 'きよ' },
        { original: 'Kanagawa K',
          locale: 'ja',
          given: 'K',
          given_kana: '',
          surname: 'Kanagawa',
          surname_kana: 'かながわ',
          name: 'Kanagawa K',
          ascii: 'Kanagawa K',
          plain: 'Kanagawa K' },
        { original: 'Can be read Daiko',
          locale: 'ja',
          given: 'Daiko',
          given_kana: 'だいこ',
          name: 'Daiko',
          ascii: 'Daiko',
          plain: 'Daiko',
          kana: 'だいこ' },
        { original: 'Keirin Signed',
          locale: 'ja',
          given: 'Keirin',
          given_kana: 'けいりん',
          name: 'Keirin',
          ascii: 'Keirin',
          plain: 'Keirin',
          kana: 'けいりん' },
        { original: 'Signed K. Yukiko',
          locale: 'ja',
          given: 'Yukiko',
          given_kana: 'ゆきこ',
          surname: 'K',
          surname_kana: '',
          name: 'K Yukiko',
          ascii: 'K Yukiko',
          plain: 'K Yukiko',
          kana: 'ゆきこ' },
        { original: 'Signature may be translated as RYOMI',
          locale: 'ja',
          given: 'Ryomi',
          given_kana: 'りょみ',
          name: 'Ryomi',
          ascii: 'Ryomi',
          plain: 'Ryomi',
          kana: 'りょみ' },
        { original: 'Unread', locale: '', unknown: true },
        { original: 'Signature and seal not read',
          locale: '',
          unknown: true },
        { original: 'No signature', locale: '', unknown: true },
        { original: 'Not identified', locale: '', unknown: true },
        { original: 'Unsigned Shunga', locale: '', unknown: true },
        { original: 'UNSIGNED', locale: '', unknown: true },
        { original: 'ANSIGNED', locale: '', unknown: true },
        { original: 'Koho Ohuchi',
          locale: 'ja',
          given: 'Kōhō',
          given_kana: 'こおほお',
          surname: 'Ōuchi',
          surname_kana: 'おおうち',
          name: 'Ōuchi Kōhō',
          ascii: 'Ōuchi Koohoo',
          plain: 'Ōuchi Koho',
          kana: 'おおうちこおほお' },
        { original: 'SYOTEI Hokuzyu',
          locale: 'ja',
          given: 'Shōtei',
          given_kana: 'しょおてい',
          surname: 'Hokujū',
          surname_kana: 'ほくじゅう',
          name: 'Hokujū Shōtei',
          ascii: 'Hokujuu Shootei',
          plain: 'Hokuju Shotei',
          kana: 'ほくじゅうしょおてい' },
        { original: 'SENCYUSYA Kuniuma',
          locale: 'ja',
          surname: 'Senchusha',
          surname_kana: 'せんちゅしゃ',
          given: 'Kuniuma',
          given_kana: 'くにうま',
          name: 'Senchusha Kuniuma',
          ascii: 'Senchusha Kuniuma',
          plain: 'Senchusha Kuniuma',
          kana: 'せんちゅしゃくにうま' },
        { original: 'Kohusai',
          locale: 'ja',
          given: 'Kōusai',
          given_kana: 'こおうさい',
          name: 'Kōusai',
          ascii: 'Koousai',
          plain: 'Kousai',
          kana: 'こおうさい' },
        { original: 'CYOBUNSAI Eishi',
          locale: 'ja',
          given: 'Eishi',
          given_kana: 'えいし',
          surname: 'Chōbunsai',
          surname_kana: 'ちょおぶんさい',
          name: 'Chōbunsai Eishi',
          ascii: 'Choobunsai Eishi',
          plain: 'Chobunsai Eishi',
          kana: 'ちょおぶんさいえいし' },
        { original: 'UTAGAWA Yoshihuji',
          locale: 'ja',
          given: 'Yoshifuji',
          given_kana: 'よしふじ',
          surname: 'Utagawa',
          surname_kana: 'うたがわ',
          name: 'Utagawa Yoshifuji',
          ascii: 'Utagawa Yoshifuji',
          plain: 'Utagawa Yoshifuji',
          kana: 'うたがわよしふじ' },
        { original: 'SYOSAI Ikkei',
          locale: 'ja',
          given: 'Ikkei',
          given_kana: 'いっけい',
          surname: 'Shōsai',
          surname_kana: 'しょおさい',
          name: 'Shōsai Ikkei',
          ascii: 'Shoosai Ikkei',
          plain: 'Shosai Ikkei',
          kana: 'しょおさいいっけい' },
        { original: 'KATSUKAWA Syunnei',
          locale: 'ja',
          given: 'Shun\'ei',
          given_kana: 'しゅんえい',
          surname: 'Katsukawa',
          surname_kana: 'かつかわ',
          name: 'Katsukawa Shun\'ei',
          ascii: 'Katsukawa Shun\'ei',
          plain: 'Katsukawa Shun\'ei',
          kana: 'かつかわしゅんえい' },
        { original: 'Isoda Koryu_sai',
          locale: 'ja',
          given: 'Koryūsai',
          given_kana: 'こりゅうさい',
          surname: 'Isoda',
          surname_kana: 'いそだ',
          name: 'Isoda Koryūsai',
          ascii: 'Isoda Koryuusai',
          plain: 'Isoda Koryusai',
          kana: 'いそだこりゅうさい' },
        { original: 'Toyokuni III & Hiroshige',
          locale: 'ja',
          generation: 3,
          given: 'Toyokuni',
          given_kana: 'とよくに',
          name: 'Toyokuni III',
          ascii: 'Toyokuni III',
          plain: 'Toyokuni III',
          kana: 'とよくに' },
        { original: 'Hiroshige/Toyokuni III',
          locale: 'ja',
          options: { stripParens: true },
          given: 'Hiroshige',
          given_kana: 'ひろしげ',
          name: 'Hiroshige',
          ascii: 'Hiroshige',
          plain: 'Hiroshige',
          kana: 'ひろしげ' },
        { original: 'Hiroshige and Toyokuni III',
          locale: 'ja',
          given: 'Hiroshige',
          given_kana: 'ひろしげ',
          name: 'Hiroshige',
          ascii: 'Hiroshige',
          plain: 'Hiroshige',
          kana: 'ひろしげ' },
        { original: 'Ichiryusai HIROSHIGE ET AL',
          locale: 'ja',
          given: 'Hiroshige',
          given_kana: 'ひろしげ',
          surname: 'Ichiryūsai',
          surname_kana: 'いちりゅうさい',
          name: 'Ichiryūsai Hiroshige',
          ascii: 'Ichiryuusai Hiroshige',
          plain: 'Ichiryusai Hiroshige',
          kana: 'いちりゅうさいひろしげ' },
        { original: 'Formerly Attributed to Utagawa Hiroshige (Japanese, 1797–1858)',
          locale: 'ja',
          attributed: true,
          given: 'Hiroshige',
          given_kana: 'ひろしげ',
          surname: 'Utagawa',
          surname_kana: 'うたがわ',
          name: 'Utagawa Hiroshige',
          ascii: 'Utagawa Hiroshige',
          plain: 'Utagawa Hiroshige',
          kana: 'うたがわひろしげ' },
        { original: 'Shuntei (att)',
          locale: 'ja',
          attributed: true,
          given: 'Shuntei',
          given_kana: 'しゅんてい',
          name: 'Shuntei',
          ascii: 'Shuntei',
          plain: 'Shuntei',
          kana: 'しゅんてい' },
        { original: 'Woodblock for a print designed by Utagawa Toyokuni I (Japanese, 1769–1825)',
          locale: 'ja',
          given: 'Toyokuni',
          given_kana: 'とよくに',
          surname: 'Utagawa',
          surname_kana: 'うたがわ',
          name: 'Utagawa Toyokuni',
          ascii: 'Utagawa Toyokuni',
          plain: 'Utagawa Toyokuni',
          kana: 'うたがわとよくに' },
        { original: 'Original print designed by Utagawa Hiroshige (Japanese, 1797–1858)',
         locale: 'ja',
         after: true,
         given: 'Hiroshige',
         given_kana: 'ひろしげ',
         surname: 'Utagawa',
         surname_kana: 'うたがわ',
         name: 'Utagawa Hiroshige',
         ascii: 'Utagawa Hiroshige',
         plain: 'Utagawa Hiroshige',
         kana: 'うたがわひろしげ' },
        { original: 'In the Style of Utagawa Hiroshige (Japanese, 1797–1858)',
          locale: 'ja',
          after: true,
          given: 'Hiroshige',
          given_kana: 'ひろしげ',
          surname: 'Utagawa',
          surname_kana: 'うたがわ',
          name: 'Utagawa Hiroshige',
          ascii: 'Utagawa Hiroshige',
          plain: 'Utagawa Hiroshige',
          kana: 'うたがわひろしげ' },
        { original: '', locale: 'ja', unknown: true },
        { original: '-', locale: 'ja', unknown: true },
        { original: '耕けい',
          locale: 'ja',
          kanji: '耕けい' },
        { original: '無落款', locale: '', unknown: true },
        { original: '無落款', locale: '', unknown: true },
        { original: '不明', locale: '', unknown: true },
        { original: 'なし', locale: '', unknown: true },
        { original: 'None',
          locale: '',
          unknown: true },
        { original: 'Kiyotada VII',
          locale: 'ja',
          generation: 7,
          given: 'Kiyotada',
          given_kana: 'きよただ',
          name: 'Kiyotada VII',
          ascii: 'Kiyotada VII',
          plain: 'Kiyotada VII',
          kana: 'きよただ' },
        { original: 'Not signed',
          locale: '',
          unknown: true },
        { original: '年豊？',
          locale: 'ja',
          kanji: '年豊？' },
        { original: '芳？',
          locale: 'ja',
          kanji: '芳？',
          given_kanji: '芳？' },
        { original: '国☆',
          locale: 'ja',
          kanji: '国☆',
          given_kanji: '国☆' },
        { original: 'Various artists',
          locale: '',
          unknown: true },
        { original: 'M. Uchiyama',
          locale: 'ja',
          given: 'M',
          given_kana: 'ん',
          surname: 'Uchiyama',
          surname_kana: 'うちやま',
          name: 'Uchiyama M',
          ascii: 'Uchiyama M',
          plain: 'Uchiyama M',
          kana: 'うちやまん' },
        { original: 'Kanda, M.',
          locale: 'ja',
          given: 'M',
          given_kana: 'ん',
          surname: 'Kanda',
          surname_kana: 'かんだ',
          name: 'Kanda M',
          ascii: 'Kanda M',
          plain: 'Kanda M',
          kana: 'かんだん' },
        { original: 'School of Harunobu (Suzuki Harunobu 1725–1770)',
          locale: 'ja',
          school: true,
          given: 'Harunobu',
          given_kana: 'はるのぶ',
          name: 'Harunobu',
          ascii: 'Harunobu',
          plain: 'Harunobu',
          kana: 'はるのぶ' },
        { original: 'Torii School',
          locale: 'ja',
          school: true,
          surname: 'Torii' },
        { original: 'Attributed to Zeshin 91807-91)',
          locale: 'ja',
          attributed: true,
          given: 'Zeshin',
          given_kana: 'ぜしん',
          name: 'Zeshin',
          ascii: 'Zeshin',
          plain: 'Zeshin',
          kana: 'ぜしん' },
        { original: 'Attributed to Hirezaki Eiho',
          locale: 'ja',
          attributed: true,
          given: 'Eihō',
          given_kana: 'えいほお',
          surname: 'Hirezaki',
          surname_kana: 'ひれざき',
          name: 'Hirezaki Eihō',
          ascii: 'Hirezaki Eihoo',
          plain: 'Hirezaki Eiho',
          kana: 'ひれざきえいほお' },
        { original: 'After Yamamura, Toyonari',
          locale: 'ja',
          after: true,
          given: 'Toyonari',
          given_kana: 'とよなり',
          surname: 'Yamamura',
          surname_kana: 'やまむら',
          name: 'Yamamura Toyonari',
          ascii: 'Yamamura Toyonari',
          plain: 'Yamamura Toyonari',
          kana: 'やまむらとよなり' },
        { original: 'After Buncho',
          locale: 'ja',
          after: true,
          given: 'Buncho',
          given_kana: 'ぶんちょ',
          name: 'Buncho',
          ascii: 'Buncho',
          plain: 'Buncho',
          kana: 'ぶんちょ' },
        { original: 'Artist unidentified', locale: '', unknown: true },
        { original: 'Artist unknown', locale: '', unknown: true },
        { original: 'Anonymous', locale: '', unknown: true },
        { original: 'Signature on title page not read',
          locale: '',
          unknown: true },
        { original: '歌川広重 (2代目)',
          locale: 'ja',
          generation: 2,
          kanji: '歌川広重 (2代目)',
          surname_kanji: '歌川',
          given_kanji: '広重' },
        { original: 'Torii Kiyomine (Kiyomitsu II 二代目鳥居清満)',
          locale: 'ja',
          surname: 'Torii',
          surname_kana: 'とりい',
          given: 'Kiyomine',
          given_kana: 'きよみね',
          name: 'Torii Kiyomine',
          ascii: 'Torii Kiyomine',
          plain: 'Torii Kiyomine',
          kana: 'とりいきよみね'},
        { original: 'Kunisada 1, Utagawa 歌川国貞-豊国三代',
          locale: 'ja',
          kanji: '歌川国貞',
          given: 'Kunisada',
          given_kana: 'くにさだ',
          surname: 'Utagawa',
          surname_kana: 'うたがわ',
          given_kanji: '国貞',
          surname_kanji: '歌川',
          name: 'Utagawa Kunisada',
          ascii: 'Utagawa Kunisada',
          plain: 'Utagawa Kunisada',
          kana: 'うたがわくにさだ' },
        { original: 'Yamashita Shintaro (1881-1966) — 山下 新太郎',
          locale: 'ja',
          surname_kanji: '山下',
          given_kanji: '新太郎',
          kanji: '山下新太郎',
          given: 'Shintarō',
          given_kana: 'しんたろお',
          surname: 'Yamashita',
          surname_kana: 'やました',
          name: 'Yamashita Shintarō',
          ascii: 'Yamashita Shintaroo',
          plain: 'Yamashita Shintaro',
          kana: 'やましたしんたろお' },
        { original: 'Shima Tamami — 島 珠実',
          locale: 'ja',
          surname_kanji: '島実',
          given_kanji: '珠',
          kanji: '島実珠',
          given: 'Tamami',
          given_kana: 'たまみ',
          surname: 'Shima',
          surname_kana: 'しま',
          name: 'Shima Tamami',
          ascii: 'Shima Tamami',
          plain: 'Shima Tamami',
          kana: 'しまたまみ' },
        { original: '柳川重信〈２〉',
          locale: 'ja',
          kanji: '柳川重信 (2代目)',
          generation: 2,
          surname_kanji: '柳川',
          given_kanji: '重信' },
        { original: 'Gigadō Ashiyuki 戯画堂 芦幸',
          locale: 'ja',
          surname_kanji: '戯画堂',
          given_kanji: '芦幸',
          kanji: '戯画堂芦幸',
          surname: 'Gigadō',
          surname_kana: 'ぎがどお',
          given: 'Ashiyuki',
          given_kana: 'あしゆき',
          name: 'Gigadō Ashiyuki',
          ascii: 'Gigadoo Ashiyuki',
          plain: 'Gigado Ashiyuki',
          kana: 'ぎがどおあしゆき' },
        { original: 'Gigadō Ashiyuki 戯画堂芦幸',
          locale: 'ja',
          kanji: '戯画堂芦幸',
          surname: 'Gigadō',
          surname_kana: 'ぎがどお',
          given: 'Ashiyuki',
          given_kana: 'あしゆき',
          name: 'Gigadō Ashiyuki',
          ascii: 'Gigadoo Ashiyuki',
          plain: 'Gigado Ashiyuki',
          kana: 'ぎがどおあしゆき' },
        { original: 'Toyoshige II (豊重　二代)',
          locale: 'ja',
          generation: 2,
          kanji: '豊重 (2代目)',
          given: 'Toyoshige',
          given_kana: 'とよしげ',
          given_kanji: '豊重',
          name: 'Toyoshige II',
          ascii: 'Toyoshige II',
          plain: 'Toyoshige II',
          kana: 'とよしげ' },
        { original: 'Hiroshige II 歌川広重 (2代目)',
          locale: 'ja',
          kanji: '歌川広重 (2代目)',
          generation: 2,
          given: 'Hiroshige',
          given_kana: 'ひろしげ',
          given_kanji: '広重',
          surname_kanji: '歌川',
          name: 'Hiroshige II',
          ascii: 'Hiroshige II',
          plain: 'Hiroshige II',
          kana: 'ひろしげ' },
        { original: 'Ike no Taiga (池大雅)',
          locale: 'ja',
          kanji: '池大雅',
          middle: 'No',
          given: 'Taiga',
          given_kana: 'たいが',
          surname: 'Ike',
          surname_kana: 'いけ',
          given_kanji: '大雅',
          surname_kanji: '池',
          name: 'Ike No Taiga',
          ascii: 'Ike No Taiga',
          plain: 'Ike No Taiga',
          kana: 'いけたいが' },
        { original: 'Romeo V. Tabuena',
          locale: '',
          given: 'Romeo',
          surname: 'Tabuena',
          middle: 'V.',
          name: 'Romeo V. Tabuena',
          ascii: 'Romeo V. Tabuena',
          plain: 'Romeo V. Tabuena' },
        { original: 'Oskar J. A. V. RIESENTHAL',
          locale: '',
          given: 'Oskar',
          surname: 'Riesenthal',
          middle: 'J. A. V.',
          name: 'Oskar J. A. V. Riesenthal',
          ascii: 'Oskar J. A. V. Riesenthal',
          plain: 'Oskar J. A. V. Riesenthal' },
        { original: 'Oskar J. A. RIESENTHAL',
          locale: '',
          given: 'Oskar',
          surname: 'Riesenthal',
          middle: 'J. A.',
          name: 'Oskar J. A. Riesenthal',
          ascii: 'Oskar J. A. Riesenthal',
          plain: 'Oskar J. A. Riesenthal' },
        { original: 'Juliette May Fraser',
          locale: '',
          given: 'Juliette',
          surname: 'Fraser',
          middle: 'May',
          name: 'Juliette May Fraser',
          ascii: 'Juliette May Fraser',
          plain: 'Juliette May Fraser' },
        { original: 'Shun-ei Katsukawa',
          locale: 'ja',
          given: 'Shun-ei',
          given_kana: 'しゅねい',
          surname: 'Katsukawa',
          surname_kana: 'かつかわ',
          name: 'Katsukawa Shun-ei',
          ascii: 'Katsukawa Shun-ei',
          plain: 'Katsukawa Shun-ei',
          kana: 'かつかわしゅねい' },
        { original: 'Tori-jo',
          locale: 'ja',
          given: 'Tori-jo',
          given_kana: 'とりじょ',
          name: 'Tori-jo',
          ascii: 'Tori-jo',
          plain: 'Tori-jo',
          kana: 'とりじょ' },
        { original: 'Hachisuka Kuniaki II (国明二代)',
          locale: 'ja',
          generation: 2,
          kanji: '国明 (2代目)',
          given: 'Kuniaki',
          given_kana: 'くにあき',
          surname: 'Hachisuka',
          surname_kana: 'はちすか',
          given_kanji: '国明',
          name: 'Hachisuka Kuniaki II',
          ascii: 'Hachisuka Kuniaki II',
          plain: 'Hachisuka Kuniaki II',
          kana: 'はちすかくにあき' },
        { original: 'Sakamoto Hanjiro (坂本繁二郎)',
          locale: 'ja',
          kanji: '坂本繁二郎',
          given: 'Hanjirō',
          given_kana: 'はんじろお',
          surname: 'Sakamoto',
          surname_kana: 'さかもと',
          given_kanji: '繁二郎',
          surname_kanji: '坂本',
          name: 'Sakamoto Hanjirō',
          ascii: 'Sakamoto Hanjiroo',
          plain: 'Sakamoto Hanjiro',
          kana: 'さかもとはんじろお' },
        { original: 'Utagawa Kunisada II (二代歌川国貞)',
          locale: 'ja',
          kanji: '歌川国貞 (2代目)',
          generation: 2,
          given: 'Kunisada',
          given_kana: 'くにさだ',
          surname: 'Utagawa',
          surname_kana: 'うたがわ',
          given_kanji: '国貞',
          surname_kanji: '歌川',
          name: 'Utagawa Kunisada II',
          ascii: 'Utagawa Kunisada II',
          plain: 'Utagawa Kunisada II',
          kana: 'うたがわくにさだ' },
        { original: 'Asano Takeji (浅野竹二)',
          locale: 'ja',
          kanji: '竹二浅野',
          given: 'Asano',
          given_kana: 'あさの',
          surname: 'Takeji',
          surname_kana: 'たけじ',
          given_kanji: '浅野',
          surname_kanji: '竹二',
          name: 'Takeji Asano',
          ascii: 'Takeji Asano',
          plain: 'Takeji Asano',
          kana: 'たけじあさの' },
        { original: 'Tokuu',
          locale: 'ja',
          given: 'Tokū',
          given_kana: 'とくう',
          name: 'Tokū',
          ascii: 'Tokuu',
          plain: 'Toku',
          kana: 'とくう' },
        { original: 'Ryûkôsai',
          locale: 'ja',
          given: 'Ryūkōsai',
          given_kana: 'りゅうこおさい',
          name: 'Ryūkōsai',
          ascii: 'Ryuukoosai',
          plain: 'Ryukosai',
          kana: 'りゅうこおさい' },
        { original: 'Utagawa Kunitomi (国富 Toyokuni II)',
          locale: 'ja',
          kanji: '国富',
          given: 'Kunitomi',
          given_kana: 'くにとみ',
          surname: 'Utagawa',
          surname_kana: 'うたがわ',
          given_kanji: '国富',
          name: 'Utagawa Kunitomi',
          ascii: 'Utagawa Kunitomi',
          plain: 'Utagawa Kunitomi',
          kana: 'うたがわくにとみ' },
        { original: 'Kunisada IV Utagawa',
          locale: 'ja',
          generation: 4,
          given: 'Kunisada',
          given_kana: 'くにさだ',
          surname: 'Utagawa',
          surname_kana: 'うたがわ',
          name: 'Utagawa Kunisada IV',
          ascii: 'Utagawa Kunisada IV',
          plain: 'Utagawa Kunisada IV',
          kana: 'うたがわくにさだ' },
        { original: 'Utagawa Kunisada IV (1800-1900)',
          locale: 'ja',
          generation: 4,
          given: 'Kunisada',
          given_kana: 'くにさだ',
          surname: 'Utagawa',
          surname_kana: 'うたがわ',
          name: 'Utagawa Kunisada IV',
          ascii: 'Utagawa Kunisada IV',
          plain: 'Utagawa Kunisada IV',
          kana: 'うたがわくにさだ' },
        { original: 'Utagawa Kuniyoshi (歌川国芳) (Kuniyoshi, Utagawa)',
          locale: 'ja',
          options: { stripParens: true },
          given: 'Kuniyoshi',
          given_kana: 'くによし',
          surname: 'Utagawa',
          surname_kana: 'うたがわ',
          name: 'Utagawa Kuniyoshi',
          ascii: 'Utagawa Kuniyoshi',
          plain: 'Utagawa Kuniyoshi',
          kana: 'うたがわくによし' },
        { original: 'Hiroshige',
          locale: 'ja',
          options: { givenFirst: true },
          given: 'Hiroshige',
          given_kana: 'ひろしげ',
          name: 'Hiroshige',
          ascii: 'Hiroshige',
          plain: 'Hiroshige',
          kana: 'ひろしげ' },
        // Fo is not valid!
        { original: 'Tsuguharu Foujita',
          locale: '',
          given: 'Tsuguharu',
          surname: 'Foujita',
          name: 'Tsuguharu Foujita',
          ascii: 'Tsuguharu Foujita',
          plain: 'Tsuguharu Foujita' },
        { original: 'Shibata Zeshin (柴田是眞)',
          locale: 'ja',
          kanji: '柴田是眞',
          given: 'Zeshin',
          given_kana: 'ぜしん',
          surname: 'Shibata',
          surname_kana: 'しばた',
          surname_kanji: '柴田',
          given_kanji: '是眞',
          name: 'Shibata Zeshin',
          ascii: 'Shibata Zeshin',
          plain: 'Shibata Zeshin',
          kana: 'しばたぜしん' },
        { original: 'FUKAZAWA Gunji',
          locale: 'ja',
          given: 'Gunji',
          given_kana: 'ぐんじ',
          surname: 'Fukazawa',
          surname_kana: 'ふかざわ',
          name: 'Fukazawa Gunji',
          ascii: 'Fukazawa Gunji',
          plain: 'Fukazawa Gunji',
          kana: 'ふかざわぐんじ' },
        { original: 'Torii Kiyonaga',
          locale: 'ja',
          given: 'Kiyonaga',
          given_kana: 'きよなが',
          surname: 'Torii',
          surname_kana: 'とりい',
          name: 'Torii Kiyonaga',
          ascii: 'Torii Kiyonaga',
          plain: 'Torii Kiyonaga',
          kana: 'とりいきよなが' },
        { original: 'Toyokuni UTAGAWA',
          locale: 'ja',
          options: { givenFirst: true },
          given: 'Toyokuni',
          given_kana: 'とよくに',
          surname: 'Utagawa',
          surname_kana: 'うたがわ',
          name: 'Utagawa Toyokuni',
          ascii: 'Utagawa Toyokuni',
          plain: 'Utagawa Toyokuni',
          kana: 'うたがわとよくに' },
        { original: 'Toyokuni UTAGAWA',
          locale: 'ja',
          given: 'Toyokuni',
          given_kana: 'とよくに',
          surname: 'Utagawa',
          surname_kana: 'うたがわ',
          name: 'Utagawa Toyokuni',
          ascii: 'Utagawa Toyokuni',
          plain: 'Utagawa Toyokuni',
          kana: 'うたがわとよくに' },
        { original: 'Charles W Bartlett',
          locale: '',
          given: 'Charles',
          surname: 'Bartlett',
          middle: 'W.',
          name: 'Charles W. Bartlett',
          ascii: 'Charles W. Bartlett',
          plain: 'Charles W. Bartlett' },
        { original: 'Toyokuni IV',
          locale: 'ja',
          generation: 4,
          given: 'Toyokuni',
          given_kana: 'とよくに',
          name: 'Toyokuni IV',
          ascii: 'Toyokuni IV',
          plain: 'Toyokuni IV',
          kana: 'とよくに' },
        { original: 'Hiroshige Utagawa',
          locale: 'ja',
          given: 'Hiroshige',
          given_kana: 'ひろしげ',
          surname: 'Utagawa',
          surname_kana: 'うたがわ',
          name: 'Utagawa Hiroshige',
          ascii: 'Utagawa Hiroshige',
          plain: 'Utagawa Hiroshige',
          kana: 'うたがわひろしげ' },
        { original: 'Hiroshige Andō',
          locale: 'ja',
          given: 'Hiroshige',
          given_kana: 'ひろしげ',
          surname: 'Andō',
          surname_kana: 'あんどお',
          name: 'Andō Hiroshige',
          ascii: 'Andoo Hiroshige',
          plain: 'Ando Hiroshige',
          kana: 'あんどおひろしげ' },
        { original: 'Kunitsuru Utagawa',
          locale: 'ja',
          given: 'Kunitsuru',
          given_kana: 'くにつる',
          surname: 'Utagawa',
          surname_kana: 'うたがわ',
          name: 'Utagawa Kunitsuru',
          ascii: 'Utagawa Kunitsuru',
          plain: 'Utagawa Kunitsuru',
          kana: 'うたがわくにつる' },
        { original: 'Toyoshige II, Utagawa',
          locale: 'ja',
          generation: 2,
          given: 'Toyoshige',
          given_kana: 'とよしげ',
          surname: 'Utagawa',
          surname_kana: 'うたがわ',
          name: 'Utagawa Toyoshige II',
          ascii: 'Utagawa Toyoshige II',
          plain: 'Utagawa Toyoshige II',
          kana: 'うたがわとよしげ' },
        { original: 'Utagawa Kunitomi I (国富)',
          locale: 'ja',
          kanji: '国富',
          given: 'Kunitomi',
          given_kana: 'くにとみ',
          surname: 'Utagawa',
          surname_kana: 'うたがわ',
          given_kanji: '国富',
          name: 'Utagawa Kunitomi',
          ascii: 'Utagawa Kunitomi',
          plain: 'Utagawa Kunitomi',
          kana: 'うたがわくにとみ' },
        { original: 'Kiyonobu II (清信　二代)',
          locale: 'ja',
          generation: 2,
          kanji: '清信 (2代目)',
          given: 'Kiyonobu',
          given_kana: 'きよのぶ',
          given_kanji: '清信',
          name: 'Kiyonobu II',
          ascii: 'Kiyonobu II',
          plain: 'Kiyonobu II',
          kana: 'きよのぶ' },
        { original: '清信　二代',
          locale: 'ja',
          generation: 2,
          kanji: '清信 (2代目)',
          given_kanji: '清信' },
        { original: 'Shun\'ei Katsukawa',
          locale: 'ja',
          given: 'Shun\'ei',
          given_kana: 'しゅんえい',
          surname: 'Katsukawa',
          surname_kana: 'かつかわ',
          name: 'Katsukawa Shun\'ei',
          ascii: 'Katsukawa Shun\'ei',
          plain: 'Katsukawa Shun\'ei',
          kana: 'かつかわしゅんえい' },
        { original: 'Eishôsai Chōki',
          locale: 'ja',
          given: 'Chōki',
          given_kana: 'ちょおき',
          surname: 'Eishōsai',
          surname_kana: 'えいしょおさい',
          name: 'Eishōsai Chōki',
          ascii: 'Eishoosai Chooki',
          plain: 'Eishosai Choki',
          kana: 'えいしょおさいちょおき' },
        { original: 'Choki Eishosai',
          locale: 'ja',
          given: 'Chōki',
          given_kana: 'ちょおき',
          surname: 'Eishōsai',
          surname_kana: 'えいしょおさい',
          name: 'Eishōsai Chōki',
          ascii: 'Eishoosai Chooki',
          plain: 'Eishosai Choki',
          kana: 'えいしょおさいちょおき' },
        { original: 'Sharaku Toshusai',
          locale: 'ja',
          given: 'Sharaku',
          given_kana: 'しゃらく',
          surname: 'Tōshūsai',
          surname_kana: 'とおしゅうさい',
          name: 'Tōshūsai Sharaku',
          ascii: 'Tooshuusai Sharaku',
          plain: 'Toshusai Sharaku',
          kana: 'とおしゅうさいしゃらく' },
        { original: 'Shunei Katsukawa',
          locale: 'ja',
          given: 'Shun\'ei',
          given_kana: 'しゅんえい',
          surname: 'Katsukawa',
          surname_kana: 'かつかわ',
          name: 'Katsukawa Shun\'ei',
          ascii: 'Katsukawa Shun\'ei',
          plain: 'Katsukawa Shun\'ei',
          kana: 'かつかわしゅんえい' },
        { original: 'Charles Bartlett',
          locale: '',
          given: 'Charles',
          surname: 'Bartlett',
          name: 'Charles Bartlett',
          ascii: 'Charles Bartlett',
          plain: 'Charles Bartlett' },
        { original: 'Ma ZHONGJUN',
          locale: '',
          given: 'Ma',
          surname: 'Zhongjun',
          name: 'Ma Zhongjun',
          ascii: 'Ma Zhongjun',
          plain: 'Ma Zhongjun' },
        { original: 'Mai Li',
          locale: '',
          given: 'Li',
          surname: 'Mai',
          name: 'Li Mai',
          ascii: 'Li Mai',
          plain: 'Li Mai' },
        { original: 'Shokosai Hanbei (松好斎半兵衛)',
          locale: 'ja',
          kanji: '松好斎半兵衛',
          given: 'Hanbei',
          given_kana: 'はんべい',
          surname: 'Shōkosai',
          surname_kana: 'しょおこさい',
          given_kanji: '半兵衛',
          surname_kanji: '松好斎',
          name: 'Shōkosai Hanbei',
          ascii: 'Shookosai Hanbei',
          plain: 'Shokosai Hanbei',
          kana: 'しょおこさいはんべい' },
        { original: '(松好斎半兵衛)',
          locale: 'ja',
          kanji: '松好斎半兵衛',
          surname_kanji: '松好斎',
          given_kanji: '半兵衛' },
        { original: '歌川広重',
          locale: 'ja',
          kanji: '歌川広重',
          surname_kanji: '歌川',
          given_kanji: '広重' },
        { original: '歌川 国郷',
          locale: 'ja',
          kanji: '歌川国郷',
          surname_kanji: '歌川',
          given_kanji: '国郷' },
        { original: '柴田是眞',
          locale: 'ja',
          kanji: '柴田是眞',
          surname_kanji: '柴田',
          given_kanji: '是眞' },
        { original: '風折有丈',
          locale: 'ja',
          kanji: '風折有丈',
          surname_kanji: '風折',
          given_kanji: '有丈' }
    ];

    tests.forEach(function(expected) {
        var actual = romajiName.parseName(expected);
        try {
            assert.deepEqual(actual, expected);
        } catch(e) {
            console.log("Actual:", actual);
            console.log("Expected:", expected);
            throw e;
        }
    });

    (function() {
        var expected = { original: 'Toyokuni UTAGAWA',
          locale: 'ja',
          options: { givenFirst: false },
          given: 'Toyokuni',
          given_kana: 'とよくに',
          surname: 'Utagawa',
          surname_kana: 'うたがわ',
          name: 'Utagawa Toyokuni',
          ascii: 'Utagawa Toyokuni',
          plain: 'Utagawa Toyokuni',
          kana: 'うたがわとよくに' };
        var actual = romajiName.parseName(expected, {
            givenFirst: true
        });
        expected.options.givenFirst = true;
        try {
            assert.deepEqual(actual, expected);
        } catch(e) {
            console.log("Actual:", actual);
            console.log("Expected:", expected);
            throw e;
        }
    })();
});
